# Generated by Django 5.2.8 on 2025-11-11 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('ear_tag_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('breed', models.CharField(choices=[('LOCAL', 'Local'), ('PA', 'PA'), ('PD', 'PD'), ('AC', 'AC'), ('DC', 'DC')], max_length=10)),
                ('breed_level', models.FloatField()),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('type', models.CharField(choices=[('LAMB', 'Lamb'), ('YOUNG_RAM', 'Young Ram'), ('GIMMER', 'Gimmer'), ('RAM', 'Ram'), ('EWE', 'Ewe')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('birth_weight', models.FloatField(blank=True, null=True)),
                ('separation_date', models.DateField(blank=True, null=True)),
                ('separation_weight', models.FloatField(blank=True, null=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('health_notes', models.TextField(blank=True)),
                ('flagged_for_culling', models.BooleanField(default=False)),
                ('culling_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_ewe', models.ForeignKey(blank=True, limit_choices_to={'sex': 'FEMALE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ewe_offspring', to='sh_app.sheep')),
                ('parent_ram', models.ForeignKey(blank=True, limit_choices_to={'sex': 'MALE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram_offspring', to='sh_app.sheep')),
            ],
        ),
    ]
