# Generated by Django 5.2.8 on 2025-11-13 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingCycle',
            fields=[
                ('cycle_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=15)),
                ('actual_birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ewe', models.ForeignKey(limit_choices_to={'is_healthy': True, 'sex': 'FEMALE', 'type__in': ['EWE', 'GIMMER']}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_cycles_as_ewe', to='sh_app.sheep')),
                ('ram', models.ForeignKey(limit_choices_to={'is_healthy': True, 'sex': 'MALE', 'type__in': ['RAM', 'YOUNG_RAM']}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_cycles_as_ram', to='sh_app.sheep')),
            ],
        ),
    ]
