# Generated by Django 5.2.8 on 2025-11-19 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0002_breedingcycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='breedingcycle',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='breedingcycle',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='breedingcycle',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='breedingcycle',
            name='cycle_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='breedingcycle',
            name='ewe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_cycles_as_ewe', to='sh_app.sheep'),
        ),
        migrations.AlterField(
            model_name='breedingcycle',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_cycles_as_ram', to='sh_app.sheep'),
        ),
        migrations.AlterField(
            model_name='breedingcycle',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20),
        ),
    ]
