# Generated by Django 5.2.8 on 2025-11-19 11:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sh_app', '0003_auditlog_breedingcycle_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('breeding_season', models.CharField(max_length=50)),
                ('report_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='breedingcycle',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_cycles_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='log_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='notes',
            field=models.TextField(blank=True, default=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CullingRecord',
            fields=[
                ('record_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sh_app.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionRecord',
            fields=[
                ('record_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('distribution_date', models.DateField()),
                ('farmer_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheep', models.ForeignKey(limit_choices_to={'type': 'YOUNG_RAM'}, on_delete=django.db.models.deletion.CASCADE, to='sh_app.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('record_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('date_of_death', models.DateField()),
                ('cause_of_death', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sh_app.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('BREEDER', 'Breeder')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='sh_app_user_set', related_query_name='sh_app_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='sh_app_user_set', related_query_name='sh_app_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sh_app.user'),
            preserve_default=False,
        ),
    ]
