# Generated by Django 5.2.8 on 2025-11-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0004_report_remove_auditlog_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='state',
            field=models.CharField(choices=[('SILENT', 'Silent'), ('FLASHING', 'Flashing'), ('BREEDING', 'Breeding'), ('PREGNANT', 'Pregnant'), ('BIRTHING', 'Birthing')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
