# Generated by Django 5.2.8 on 2025-11-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0005_sheep_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheep',
            name='state',
            field=models.CharField(choices=[('SCILENT', 'Scilent'), ('FLASHING', 'Flashing'), ('BREEDING', 'Breeding'), ('PREGNANT', 'Pregnant'), ('BIRTHING', 'Birthing')], max_length=10),
        ),
    ]
