# Generated by Django 5.2.8 on 2025-11-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0006_alter_sheep_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheep',
            name='state',
            field=models.CharField(choices=[('SCILENT', 'Scilent'), ('FLASHING', 'Flashing'), ('BREEDING', 'Breeding'), ('PREGNANT', 'Pregnant'), ('BIRTHING', 'Birthing')], default='SCILENT', max_length=10),
        ),
    ]
