# Generated by Django 5.2.8 on 2025-11-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0007_alter_sheep_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingcycle',
            name='cycle_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
