# Generated by Django 5.2.8 on 2025-11-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0008_alter_breedingcycle_cycle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheep',
            name='state',
            field=models.CharField(choices=[('IN_ACTIVE', 'In_active'), ('ACTIVE', 'Active'), ('FLASHING', 'Flashing'), ('BREEDING', 'Breeding'), ('PREGNANT', 'Pregnant'), ('BIRTHING', 'Birthing')], default='SCILENT', max_length=10),
        ),
    ]
