# Generated by Django 5.2.8 on 2025-11-30 12:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0009_alter_sheep_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cullingrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cullingrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cullingrecord',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='distributionrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='distributionrecord',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='distributionrecord',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='mortalityrecord',
            name='cause_of_death',
        ),
        migrations.RemoveField(
            model_name='mortalityrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mortalityrecord',
            name='record_id',
        ),
        migrations.AddField(
            model_name='cullingrecord',
            name='date_culled',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cullingrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='distributionrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='reason',
            field=models.TextField(default='Initial Record'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cullingrecord',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cullingrecord',
            name='sheep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culling_records', to='sh_app.sheep'),
        ),
        migrations.AlterField(
            model_name='distributionrecord',
            name='distribution_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='distributionrecord',
            name='sheep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_records', to='sh_app.sheep'),
        ),
        migrations.AlterField(
            model_name='mortalityrecord',
            name='date_of_death',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mortalityrecord',
            name='sheep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='sh_app.sheep'),
        ),
    ]
