# Generated by Django 5.2.8 on 2025-12-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0010_remove_cullingrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheep',
            name='state',
            field=models.CharField(choices=[('IN_ACTIVE', 'In_active'), ('ACTIVE', 'Active'), ('FLASHING', 'Flashing'), ('BREEDING', 'Breeding'), ('PREGNANT', 'Pregnant'), ('BIRTHING', 'Birthing')], default='ACTIVE', max_length=10),
        ),
    ]
