# Generated by Django 5.2.8 on 2025-12-03 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0011_alter_sheep_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheep',
            old_name='breed_level',
            new_name='blood_level',
        ),
    ]
