# Generated by Django 5.2.8 on 2025-12-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0012_rename_breed_level_sheep_blood_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheep',
            old_name='separation_date',
            new_name='weaning_date',
        ),
        migrations.RenameField(
            model_name='sheep',
            old_name='separation_weight',
            new_name='weaning_weight',
        ),
    ]
